/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "face_cluster_constants.h"



const face_clusterConstants g_face_cluster_constants;

face_clusterConstants::face_clusterConstants() {
}



