/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef face_cluster_CONSTANTS_H
#define face_cluster_CONSTANTS_H

#include "face_cluster_types.h"



class face_clusterConstants {
 public:
  face_clusterConstants();

};

extern const face_clusterConstants g_face_cluster_constants;



#endif
