/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "send_photo_constants.h"



const send_photoConstants g_send_photo_constants;

send_photoConstants::send_photoConstants() {
}



