/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef send_photo_CONSTANTS_H
#define send_photo_CONSTANTS_H

#include "send_photo_types.h"



class send_photoConstants {
 public:
  send_photoConstants();

};

extern const send_photoConstants g_send_photo_constants;



#endif
