/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef face_detection_CONSTANTS_H
#define face_detection_CONSTANTS_H

#include "face_detection_types.h"



class face_detectionConstants {
 public:
  face_detectionConstants();

};

extern const face_detectionConstants g_face_detection_constants;



#endif
