/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "face_detection_constants.h"



const face_detectionConstants g_face_detection_constants;

face_detectionConstants::face_detectionConstants() {
}



